"""
aggro_tracker.py

DISABLED -- kept only so the reason is recorded where anyone would look
before rebuilding it.

This flagged a DPS/healer approaching the aggro-holder's threat. Reported
live: "kept getting alerts that everybody was pulling aggro -- not
everybody can pull aggro at one time." That report is correct, and the
feature cannot be fixed, because SWTOR's combat log does not contain the
data it needs. Measured on one real 18k-line Styrak pull:

1. ModifyThreat IS NOT A THREAT LEDGER. It fires on 108 events against
   4,859 damage events -- 2.2% -- and only for abilities that explicitly
   MODIFY threat: Dark Charge (tank stance), taunts (Threatening Scream,
   Mass Mind Control), and drops (Cloud Mind, Cover Pulse). The threat
   actually generated by damage and healing, which is nearly all of it,
   is never logged at all. Summing what IS logged is therefore dominated
   by the drops: every player finished that pull with NEGATIVE threat on
   the boss (-54,668 down to -6,317,238), including a single -6,419,384
   entry that is a threat wipe recorded as an absolute value. No tank was
   identifiable. There is no scaling or sign fix for this -- the positive
   contributions simply aren't in the file.

2. boss_target IS NOT THE AGGRO HOLDER. It tracked whoever the boss most
   recently hit, which on a cleaving/AoE boss is everyone: it changed 828
   times across 8 different players in that single pull. Whenever it
   landed on a low-threat player, every other player cleared the 90%
   ratio at once -- which is exactly the "everybody is pulling aggro"
   burst that was reported.

Also removed with it: the "Threat (TPS)" overlay, which rendered the same
unusable numbers as a per-second rate.

What the log CAN support is kept elsewhere and still works: taunt_tracker
reads the taunt events directly ("did my taunt land"), which is a real,
discrete, fully-logged fact rather than an inferred magnitude.
"""

from typing import Dict, Optional


class AggroTracker:
    """Inert. Retained so existing wiring (main.py, gui.py) and saved
    layouts keep importing cleanly; see the module docstring for why this
    can never be made to work from SWTOR's log."""

    def check(self, players: Dict[str, object], boss_target: Optional[str],
              duration: float, timer_engine) -> None:
        return

    def reset(self) -> None:
        return
